package br.univali.delgis.visao;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;


public class Bairro extends javax.swing.JDialog {
    //private DefaultTableModel modelo;

    public Bairro(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Principal = new javax.swing.JPanel();
        label_Nome = new javax.swing.JLabel();
        scrollPane_Coordenadas = new javax.swing.JScrollPane();
        table_Coordenadas = new javax.swing.JTable();
        separator = new javax.swing.JSeparator();
        label_Separador = new javax.swing.JLabel();
        button_Novo = new javax.swing.JButton();
        button_Excluir = new javax.swing.JButton();
        label_Separador1 = new javax.swing.JLabel();
        separator1 = new javax.swing.JSeparator();
        button_SalvarBairro = new javax.swing.JButton();
        button_EditarBairro = new javax.swing.JButton();
        field_Nome = new javax.swing.JTextField();
        field_Long = new javax.swing.JTextField();
        field_Lat = new javax.swing.JTextField();
        label_Long = new javax.swing.JLabel();
        label_Lat = new javax.swing.JLabel();
        button_Salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DelGIS - Novo/Editar Bairros");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        label_Nome.setText("Nome");

        table_Coordenadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Longitude", "Latitude"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Coordenadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_CoordenadasMouseClicked(evt);
            }
        });
        scrollPane_Coordenadas.setViewportView(table_Coordenadas);

        separator.setForeground(new java.awt.Color(153, 153, 153));
        separator.setToolTipText("");
        separator.setName(""); // NOI18N

        label_Separador.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Separador.setForeground(new java.awt.Color(102, 102, 102));
        label_Separador.setText("Coordenadas");

        button_Novo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_Novo.setText("Novo");
        button_Novo.setEnabled(false);
        button_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_NovoActionPerformed(evt);
            }
        });

        button_Excluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_Excluir.setText("Excluir");
        button_Excluir.setEnabled(false);
        button_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ExcluirActionPerformed(evt);
            }
        });

        label_Separador1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_Separador1.setForeground(new java.awt.Color(102, 102, 102));
        label_Separador1.setText("Informações do Bairro");

        separator1.setForeground(new java.awt.Color(153, 153, 153));
        separator1.setToolTipText("");
        separator1.setName(""); // NOI18N

        button_SalvarBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_SalvarBairro.setText("Salvar");
        button_SalvarBairro.setEnabled(false);
        button_SalvarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SalvarBairroActionPerformed(evt);
            }
        });

        button_EditarBairro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_EditarBairro.setText("Editar");
        button_EditarBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_EditarBairroActionPerformed(evt);
            }
        });

        field_Nome.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        field_Nome.setEnabled(false);
        field_Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_NomeActionPerformed(evt);
            }
        });

        field_Long.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        field_Long.setEnabled(false);
        field_Long.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_LongActionPerformed(evt);
            }
        });

        field_Lat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        field_Lat.setEnabled(false);
        field_Lat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_LatActionPerformed(evt);
            }
        });

        label_Long.setText("Longitude");

        label_Lat.setText("Latitude");

        button_Salvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        button_Salvar.setText("Salvar");
        button_Salvar.setEnabled(false);
        button_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_PrincipalLayout = new javax.swing.GroupLayout(panel_Principal);
        panel_Principal.setLayout(panel_PrincipalLayout);
        panel_PrincipalLayout.setHorizontalGroup(
            panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PrincipalLayout.createSequentialGroup()
                .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_PrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(panel_PrincipalLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addComponent(label_Separador1))
                                .addComponent(label_Nome)
                                .addComponent(field_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panel_PrincipalLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel_PrincipalLayout.createSequentialGroup()
                                            .addGap(101, 101, 101)
                                            .addComponent(button_Novo)
                                            .addGap(18, 18, 18)
                                            .addComponent(button_Excluir)
                                            .addGap(18, 18, 18)
                                            .addComponent(button_Salvar))
                                        .addGroup(panel_PrincipalLayout.createSequentialGroup()
                                            .addComponent(label_Separador)
                                            .addGap(14, 14, 14)
                                            .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(panel_PrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(field_Long, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_PrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(scrollPane_Coordenadas))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel_PrincipalLayout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(button_EditarBairro)
                            .addGap(26, 26, 26)
                            .addComponent(button_SalvarBairro)
                            .addGap(140, 140, 140))
                        .addGroup(panel_PrincipalLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label_Long)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(field_Lat, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label_Lat)))))
                .addGap(319, 319, 319))
        );
        panel_PrincipalLayout.setVerticalGroup(
            panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_PrincipalLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Separador1)
                    .addGroup(panel_PrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(separator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(label_Nome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(field_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_EditarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_SalvarBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Separador)
                    .addGroup(panel_PrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(separator, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_PrincipalLayout.createSequentialGroup()
                        .addComponent(label_Long)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(field_Long, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(field_Lat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(label_Lat))
                .addGap(18, 18, 18)
                .addComponent(scrollPane_Coordenadas, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setarBotoesNovo() {
        field_Lat.setEnabled(true);
        field_Long.setEnabled(true);
        button_Novo.setEnabled(false);
        button_Excluir.setEnabled(false);
        button_Salvar.setEnabled(true);
    }

    private void setarBotoesExcuir() {
        button_Excluir.setEnabled(false);
        field_Lat.setEnabled(false);
        field_Long.setEnabled(false);
    }

    private void setarBotoesEditarBairro() {
        field_Nome.setEnabled(true);
        button_Novo.setEnabled(true);
        button_SalvarBairro.setEnabled(true);
        button_EditarBairro.setEnabled(false);
    }

    private void setarBotoesSalvarBairro() {
        field_Nome.setEnabled(false);
        button_Novo.setEnabled(false);
        button_SalvarBairro.setEnabled(false);
        button_EditarBairro.setEnabled(true);
    }

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void field_NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_NomeActionPerformed

    private void button_EditarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_EditarBairroActionPerformed
        setarBotoesEditarBairro();
    }//GEN-LAST:event_button_EditarBairroActionPerformed

    private void button_SalvarBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SalvarBairroActionPerformed
        setarBotoesSalvarBairro();
    }//GEN-LAST:event_button_SalvarBairroActionPerformed

    private void button_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ExcluirActionPerformed
        setarBotoesExcuir();
    }//GEN-LAST:event_button_ExcluirActionPerformed

    private void button_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_NovoActionPerformed
        setarBotoesNovo();
    }//GEN-LAST:event_button_NovoActionPerformed

    private void table_CoordenadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_CoordenadasMouseClicked
//        if (evt.getClickCount() == 1) {
//            idSelecionado = Integer.parseInt((String) table_Topicos.getValueAt(table_Topicos.getSelectedRow(), 0));
//            setarBotoesConfirmar();
//        }
    }//GEN-LAST:event_table_CoordenadasMouseClicked

    private void field_LongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_LongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_LongActionPerformed

    private void field_LatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_LatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_LatActionPerformed

    private void button_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_SalvarActionPerformed


    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Bairro dialog = new Bairro(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_EditarBairro;
    private javax.swing.JButton button_Excluir;
    private javax.swing.JButton button_Novo;
    private javax.swing.JButton button_Salvar;
    private javax.swing.JButton button_SalvarBairro;
    private javax.swing.JTextField field_Lat;
    private javax.swing.JTextField field_Long;
    private javax.swing.JTextField field_Nome;
    private javax.swing.JLabel label_Lat;
    private javax.swing.JLabel label_Long;
    private javax.swing.JLabel label_Nome;
    private javax.swing.JLabel label_Separador;
    private javax.swing.JLabel label_Separador1;
    private javax.swing.JPanel panel_Principal;
    private javax.swing.JScrollPane scrollPane_Coordenadas;
    private javax.swing.JSeparator separator;
    private javax.swing.JSeparator separator1;
    private javax.swing.JTable table_Coordenadas;
    // End of variables declaration//GEN-END:variables
}
